### ISSUE TITLE
Add Ability to include Power Point, PDFs/Word docs

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/ahec-modules#12]
- this will be links to the docs themselves. When the user clicks the link, the app will download it so they can view it on their computer - the admins will upload these files via the app

**Comment by husseinm** [comment]
S3

**Comment by husseinm** [comment]
Should there be a max file size?

**Comment by husseinm** [comment]
This also applies to the videos...

**Comment by CodySwannGT** [comment]
Nah

On Friday, April 22, 2016, Mahdi Hussein notifications@github.com wrote:

> Should there be a max file size?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gunnertech/ahec-modules/issues/12#issuecomment-213628338

## 

Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
http://www.gunnertech.com/Skype: cody.swann

_CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving._
