### ISSUE TITLE
Add Ability to have multiple MP4s

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/ahec-modules#13]
I think this one overlaps with #4 with the addition that we should support more than just YouTube videos. My suggestion that we host the videos on Dropbox does not mean that the user would need a dropbox account to view them. Only that the admins would upload the videos _somewhere_ rather than the app directly and then, instead of uploading the video to the app, they would just paste the link to the video and we would embed the player in the app.

**Comment by husseinm** [comment]
stream
