### ISSUE TITLE
When a user completes the exam, the app should automatically send a certification of C.E. completion

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/ahec-modules#14]
This certification is a PDF that is personalized with the following information:
- Name: “Dr. John Doe” 
- Name of Course: "Support Surfaces"
- Course #: "#123456"
- Date completed: "March 14, 2016"
- Amount of credit: "1 hour"

For example, a simple PDF would look like this:

Dr. John Doe completed this Support Surfaces continuing education course #123456 on March 14, 2016  for 1 hour of CE credit.

**Comment by husseinm** [comment]
email on complete

**Comment by husseinm** [comment]
No need for the email - lets just show the certificate as a PDF right after the survey...

This is done, please note the amount of credit was not counted since that has never been a part of the course model as of late.
