### ISSUE TITLE
Reset Don Henry exams attempt back to 0

### ISSUE THREAD

**Issue by sampetteway** [gunnertech/ahec-modules#18]
Can you please reset Don Henry's exam attempts back to zero?
It might be nice if I as an administrator had a way to reset exams (or allow additional attempts)
And/or if easier, we could allow users 5 attempts to pass

Let me know your thoughts - however this needs a fix soon for CURO

**Comment by husseinm** [comment]
I can't find a "Don Henry" a first name of "Don" or a last name of "Henry" in the database, maybe he spelt his name differently? - can you give me something else that is unique to him? Ex. physical address, email address - or even a bunch of qualifiers such as profession.

**Comment by sampetteway** [comment]
**Dan Henry**   dahenry@curohs.com  Other   710 Decatur Street  Newton  Mississippi 39345           1981-09-19  1035    601-686-0234    Southern Care Hospice   601-683-7500    191 Northside Drive MISSISSIPPI Newton  39345   0.0 0.0 3   2016-09-28 20:18:48 UTC 34
