### ISSUE TITLE
As a User, I am able to Purchase a course.

### ISSUE THREAD

**Issue by husseinm** [gunnertech/ahec-modules#31]
This includes the requirement of locking a course to only paying users. Please note you may need to create a test course/edit an existing course for test purposes to give it a cost. So:

- As a User,
- I Login into app.
- I See the list of courses.
  - I Click on a Course.
  - I See the price of the course and a Button that says "Purchase"
    - I Click Purchase (W/ Sufficient Funds)
      - I now see the course, my wallet has been deducted appropriately, and can use the app as normal.
    -   I Click Purchase (W/O Sufficient Funds)
        - I see a text that says "Insufficient Funds - go to wallet" and am unable to use the course.

**Comment by lisa555** [comment]
I am able to login.  I see the list of courses.  The courses that have 0.00 cost allow me to register and once I select them tell me I have successfully registered.  Some of them bring me to a pre-quiz screen (I guess as part of the course).  When I click on Passed Courses it shows the three courses that start with Z and offer a certificate.  I am able to click on the certificate and it generates one to print.  Under my account everything shows correctly and I have the options to update, add to wallet or cancel my account.  I am able to populate everything in My Wallet but as you know unable to add funds.

This is the list of courses I see:

![screen shot 2017-06-02 at 10 38 42 am](https://cloud.githubusercontent.com/assets/17904239/26730717/d77240ac-477f-11e7-8a54-35a2b69ed667.png)

**Comment by lisa555** [comment]
I am unable to purchase the course for $23.00 due to my wallet issues.  This is the message I get:
![screen shot 2017-06-02 at 10 40 58 am](https://cloud.githubusercontent.com/assets/17904239/26730779/0dad350a-4780-11e7-9940-249dca3d7e2e.png)
