### ISSUE TITLE
As a user, I am able to add funds to my wallet.

### ISSUE THREAD

**Issue by husseinm** [gunnertech/ahec-modules#32]
- I Login into app.
  - I See a button in the top right that says "My Account"
    - I click that button.
    - I see a screen with an available balance and a button that says "Add Funds" under "Wallet" at the bottom of the screen.
    - I click the button.
    - I see and am put through the Stripe Payment Process.
    - I see an updated balance (including nothing if failed payment)

**Comment by husseinm** [comment]
Test Credit Card info: 4242 4242 4242 4242, any future month and year for the expiration, any three-digit number for the CVC, and any random ZIP code.

**Comment by lisa555** [comment]
I am getting this error message when trying to add funds to the Wallet.  I tried several different amounts. 25, 50, 100.
![screen shot 2017-06-02 at 10 28 45 am](https://cloud.githubusercontent.com/assets/17904239/26730380/c120308a-477e-11e7-912f-603561aa1d9e.png)

**Comment by lisa555** [comment]
Ok all working now!
