### ISSUE TITLE
User edythe.smith@halifax.org cannot log into CE courses

### ISSUE THREAD

**Issue by QualisLindaSheets** [gunnertech/ahec-modules#35]
Edythe Smith with Halifax Health Hospice reported an issue with logging into and accessing the CE courses.  She is appearing under the Course Join Requests for several courses, but Demographics is only showing her for the oxygen think tank and the dying well video.  Now when she tries to log in, it tells her access is denied.  I want to troubleshoot this as much as possible without involving her and I don't have her password, so can you please reset her password and give it to me so I can log in as her and test it?  Do you see any problems with her account setup?

**Comment by QualisLindaSheets** [comment]
I called Edythe and got her password so I could log in as her.  She is able to log in and she can see the courses listed, but when she clicks on a course, a red box appears at the top of the screen that says "Access Denied".  I did a screen capture, but I can't attach it to this ticket.

**Comment by husseinm** [comment]
Have her try again as I made a code change which should fix the bug as far as I am aware.
Also if that does not work have her try clearing her cookies & cache.
If that ALSO does not work, then let me know her password and I will try to login and test myself.

**Comment by QualisLindaSheets** [comment]
It's not working for me logging in as her.  Her password is nana@1944

**Comment by husseinm** [comment]
Try again it should be fixed. I just tested it.

**Comment by QualisLindaSheets** [comment]
I was able to register for a course that time, so issue seems to be resolved.
